### ISSUE TITLE
Fix integration tests: required key COOKIES_ENCRYPTION_KEY missing value

### ISSUE THREAD

**Issue by BarcoMasile** [canonical/identity-platform-admin-ui-operator#106]
## Description
Integration tests have been failing for a while.
One needed fix seems to be the COOKIE_ENCRYPTION_KEY missing from the env used for the tests.

There may be more fixes to perform, but that's a starting point.

**Comment by pik4ez-canonical** [comment]
From locally running Multipass VM:
```
$ PWDEBUG=1 PYTHONPATH=. tox -e integration -- tests/integration/test_charm.py::test_build_and_deploy
integration: commands[0]> playwright install
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo playwright install-deps                     ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libatk1.0-0\                ║
║         libatk-bridge2.0-0\                          ║
║         libcups2\                                    ║
║         libxcomposite1\                              ║
║         libxdamage1\                                 ║
║         libxfixes3\                                  ║
║         libxrandr2\                                  ║
║         libgbm1\                                     ║
║         libxkbcommon0\                               ║
║         libpango-1.0-0\                              ║
║         libcairo2\                                   ║
║         libasound2\                                  ║
║         libatspi2.0-0                                ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/playwright/driver/package/lib/server/registry/dependencies.js:216:9)
    at async Registry._validateHostRequirements (/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/playwright/driver/package/lib/server/registry/index.js:753:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/playwright/driver/package/lib/server/registry/index.js:851:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/playwright/driver/package/lib/server/registry/index.js:840:43)
    at async t.<anonymous> (/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/playwright/driver/package/lib/cli/program.js:137:7)
integration: commands[1]> pytest -v --tb native /home/ubuntu/identity-platform-admin-ui-operator/tests/integration --log-cli-level=INFO -s tests/integration/test_charm.py::test_build_and_deploy
===================================== test session starts =====================================
platform linux -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0 -- /home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/bin/python
cachedir: .tox/integration/.pytest_cache
rootdir: /home/ubuntu/identity-platform-admin-ui-operator
configfile: pyproject.toml
plugins: operator-0.38.0, anyio-4.6.2.post1, base-url-2.1.0, playwright-0.6.2, asyncio-0.21.2
asyncio: mode=strict
collected 1 item                                                                              

tests/integration/test_charm.py::test_build_and_deploy 
--------------------------------------- live log setup ----------------------------------------
INFO     pytest_operator.plugin:plugin.py:724 Adding model microk8s:test-charm-mi9q on cloud microk8s
INFO     oauth_tools.fixtures:fixtures.py:32 Deploying dex resources
INFO     httpx:_client.py:1027 HTTP Request: GET https://10.100.167.253:16443/api/v1/namespaces/dex "HTTP/1.1 403 Forbidden"
INFO     httpx:_client.py:1027 HTTP Request: GET https://10.100.167.253:16443/api/v1/namespaces/dex/services/dex "HTTP/1.1 403 Forbidden"
INFO     oauth_tools.external_idp:external_idp.py:121 No service found for identity provider
INFO     httpx:_client.py:1027 HTTP Request: PATCH https://10.100.167.253:16443/api/v1/namespaces/dex?force=true&fieldManager=dex-test "HTTP/1.1 403 Forbidden"
ERROR
-------------------------------------- live log teardown --------------------------------------
INFO     pytest_operator.plugin:plugin.py:903 Model status:

Model            Controller  Cloud/Region        Version  SLA          Timestamp
test-charm-mi9q  microk8s    microk8s/localhost  3.5.3    unsupported  13:54:46+02:00

INFO     pytest_operator.plugin:plugin.py:909 Juju error logs:


INFO     pytest_operator.plugin:plugin.py:926 juju-crashdump command was not found.
INFO     pytest_operator.plugin:plugin.py:1015 Resetting model test-charm-mi9q...
INFO     pytest_operator.plugin:plugin.py:1020 Not waiting on reset to complete.
INFO     pytest_operator.plugin:plugin.py:991 Forgetting model main...


=========================================== ERRORS ============================================
___________________________ ERROR at setup of test_build_and_deploy ___________________________
Traceback (most recent call last):
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 235, in raise_for_status
    resp.raise_for_status()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://10.100.167.253:16443/api/v1/namespaces/dex?force=true&fieldManager=dex-test'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 90, in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
    yield
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py", line 840, in pytest_runtest_setup
    yield from self._runtest_for(item, "setup")
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py", line 829, in _runtest_for
    yield
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py", line 875, in pytest_runtest_setup
    return (yield)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py", line 87, in pytest_runtest_setup
    yield from thread_exception_runtest_hook()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
    yield
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py", line 160, in pytest_runtest_setup
    item.session._setupstate.setup(item)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py", line 514, in setup
    col.setup()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py", line 1630, in setup
    self._request._fillfixtures()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 697, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 532, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
    fixturedef.execute(request=subrequest)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 1091, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
    teardown.throw(outcome._exception)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/setuponly.py", line 36, in pytest_fixture_setup
    return (yield)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 1140, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py", line 891, in call_fixture_func
    fixture_result = next(generator)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/oauth_tools/fixtures.py", line 33, in ext_idp_service
    ext_idp_manager = DexIdpService(client=client)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/oauth_tools/external_idp.py", line 96, in __init__
    self._apply_dex_resources()
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/oauth_tools/external_idp.py", line 150, in _apply_dex_resources
    self._client.apply(obj, force=True)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/client.py", line 757, in apply
    return self.patch(
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/client.py", line 492, in patch
    return self._client.request(
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 311, in request
    return self.handle_response(method, resp, br)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 251, in handle_response
    self.raise_for_status(resp)
  File "/home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/lightkube/core/generic_client.py", line 237, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: namespaces "dex" is forbidden: User "system:anonymous" cannot patch resource "namespaces" in API group "" in the namespace "dex"
------------------------------------- Captured log setup --------------------------------------
INFO     pytest_operator.plugin:plugin.py:724 Adding model microk8s:test-charm-mi9q on cloud microk8s
INFO     oauth_tools.fixtures:fixtures.py:32 Deploying dex resources
INFO     httpx:_client.py:1027 HTTP Request: GET https://10.100.167.253:16443/api/v1/namespaces/dex "HTTP/1.1 403 Forbidden"
INFO     httpx:_client.py:1027 HTTP Request: GET https://10.100.167.253:16443/api/v1/namespaces/dex/services/dex "HTTP/1.1 403 Forbidden"
INFO     oauth_tools.external_idp:external_idp.py:121 No service found for identity provider
INFO     httpx:_client.py:1027 HTTP Request: PATCH https://10.100.167.253:16443/api/v1/namespaces/dex?force=true&fieldManager=dex-test "HTTP/1.1 403 Forbidden"
====================================== warnings summary =======================================
tests/integration/test_charm.py::test_build_and_deploy
  /home/ubuntu/identity-platform-admin-ui-operator/.tox/integration/lib/python3.10/site-packages/httpx/_config.py:52: DeprecationWarning: `verify=<str>` is deprecated. Use `verify=ssl.create_default_context(cafile=...)` or `verify=ssl.create_default_context(capath=...)` instead.
    warnings.warn(message, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================== short test summary info ===================================
ERROR tests/integration/test_charm.py::test_build_and_deploy - lightkube.core.exceptions.ApiError: namespaces "dex" is forbidden: User "system:anonymous"...
================================ 1 warning, 1 error in 12.46s =================================
integration: exit 1 (31.69 seconds) /home/ubuntu/identity-platform-admin-ui-operator> pytest -v --tb native /home/ubuntu/identity-platform-admin-ui-operator/tests/integration --log-cli-level=INFO -s tests/integration/test_charm.py::test_build_and_deploy pid=648531
  integration: FAIL code 1 (42.31=setup[0.16]+cmd[10.46,31.69] seconds)
  evaluation failed :( (42.44 seconds)
```

**Comment by BarcoMasile** [comment]
Thank you @wood-push-melon for your work! Only comment I have is that the `macaroonbakery==1.3.4` dependency could actually be removed since the mentioned PR (from the comment) is already merged

**Comment by wood-push-melon** [comment]
> Thank you @wood-push-melon for your work! Only comment I have is that the `macaroonbakery==1.3.4` dependency could actually be removed since the mentioned PR (from the comment) is already merged, but of course no rush

yep, the TODO comment and the macaroonbakery pinned version have been removed and merged.

**Comment by wood-push-melon** [comment]
I will close this issue for now because the integration tests are fixed and running well. We can open another if something comes up.
